language: python
python: 2.7

git:
  depth: 1

install: true

script:
  - python -O -m compileall ./src/
  - find ./po -type f -name "*.po" -print -exec msgfmt {} -o {}.mo \;
  - bash ./travis_fix.sh
  - pytest
