name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.8]
    steps:
    - uses: actions/checkout@v2
      if: ${{ matrix.python-version == '2.7' }}
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      if: ${{ matrix.python-version != '2.7' }}
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        sudo apt-get install gettext
        pip install flake8 pytest
    - name: Compile python sources
      run: |
        python setup.py build --build-lib=build/lib
        python -O -m compileall build/lib/Extensions/YouTube/
    - name: Check code with flake8
      run: |
        flake8 --ignore=W191,W504,E126,E127,E128,E501 --show-source --exclude=./src/compat.py,./build
        flake8 --ignore=W191,F821,F401 --show-source --filename=./src/compat.py,./build
    - name: Remove enigma2 imports and variables for test
      run: |
        bash ./test/ci_fix.sh
    - name: Test code with pytest
      run: |
        pytest -rx -v
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get commit count
      env:
        SRCPV: $(git rev-list --count HEAD)
      if: ${{ github.event_name == 'push' && matrix.python-version == '2.7' }}
      run: |
        echo "Package version git" $SRCPV
